### ISSUE TITLE
Readme sample about PublishRelease is confusing

### ISSUE THREAD

**Issue by SuperJMN** [GeorgDangl/Nuke.GitHub#6]
Thanks for the big effort your making. The library looks awesome.

However, I'm new to nuke and I found out that pasting the sample code for `PublishRelease` is too complex to start with.

It would help a lot if you share the code of a full **Build.cs**.

For instance, the symbol `GlobDirectories` isn't recognized by the compiler. Maybe it's code for a previous version?

**Comment by GeorgDangl** [comment]
Hey @SuperJMN, thanks for raising the issue! I've added some updates in #7, would be happy to get your feedback there😀

As for an example with a full build, you can just look in the `Build.cs` file of this repository: https://github.com/GeorgDangl/Nuke.GitHub/blob/develop/build/Build.cs#L297

**Comment by SuperJMN** [comment]
Wow, that's a **good** example. I suggest you to link to it into the readme. 
BTW, GlobDirectories didn't work because I hadn't added **using static Nuke.Common.IO.Globbing**.

Congratulations on this library. It definitely helped me a lot! Big thanks!
Way to go for Nuke Build users.
